[deploy]
bucket = 'cfn-artifacts-1'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'



[parameters]

EnvFrontendUrl = 'https://gooddesignsolutions.in'
EnvBackendUrl = 'https://api.gooddesignsolutions.in'
DDBMessageTable = 'CrdDdb-DynamoDBTable-1CU4GJV08WSFJ'