AWSTemplateFormatVersion: "2010-09-09"

#VPC https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html

Resources: 
  VPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: CruddurVPC
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
       - Key: Name
         Value: CruddurIGW


#IGW
#Route-Tables
# Subnets
# Subnet A
# Subnet B
# Subnet C

